# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreMemory = channel.unary_unary(
                '/memory.MemoryService/StoreMemory',
                request_serializer=memory__pb2.StoreRequest.SerializeToString,
                response_deserializer=memory__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.SearchMemory = channel.unary_unary(
                '/memory.MemoryService/SearchMemory',
                request_serializer=memory__pb2.SearchRequest.SerializeToString,
                response_deserializer=memory__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/memory.MemoryService/DeleteMemory',
                request_serializer=memory__pb2.DeleteRequest.SerializeToString,
                response_deserializer=memory__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.SummarizeMemory = channel.unary_unary(
                '/memory.MemoryService/SummarizeMemory',
                request_serializer=memory__pb2.SummaryRequest.SerializeToString,
                response_deserializer=memory__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.Dreaming = channel.unary_unary(
                '/memory.MemoryService/Dreaming',
                request_serializer=memory__pb2.DreamRequest.SerializeToString,
                response_deserializer=memory__pb2.DreamResponse.FromString,
                _registered_method=True)
        self.GetProjectContext = channel.unary_unary(
                '/memory.MemoryService/GetProjectContext',
                request_serializer=memory__pb2.ProjectRequest.SerializeToString,
                response_deserializer=memory__pb2.ProjectResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StoreMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMemory,
                    request_deserializer=memory__pb2.StoreRequest.FromString,
                    response_serializer=memory__pb2.StoreResponse.SerializeToString,
            ),
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=memory__pb2.SearchRequest.FromString,
                    response_serializer=memory__pb2.SearchResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=memory__pb2.DeleteRequest.FromString,
                    response_serializer=memory__pb2.DeleteResponse.SerializeToString,
            ),
            'SummarizeMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeMemory,
                    request_deserializer=memory__pb2.SummaryRequest.FromString,
                    response_serializer=memory__pb2.SummaryResponse.SerializeToString,
            ),
            'Dreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.Dreaming,
                    request_deserializer=memory__pb2.DreamRequest.FromString,
                    response_serializer=memory__pb2.DreamResponse.SerializeToString,
            ),
            'GetProjectContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectContext,
                    request_deserializer=memory__pb2.ProjectRequest.FromString,
                    response_serializer=memory__pb2.ProjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.MemoryService/StoreMemory',
            memory__pb2.StoreRequest.SerializeToString,
            memory__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.MemoryService/SearchMemory',
            memory__pb2.SearchRequest.SerializeToString,
            memory__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.MemoryService/DeleteMemory',
            memory__pb2.DeleteRequest.SerializeToString,
            memory__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.MemoryService/SummarizeMemory',
            memory__pb2.SummaryRequest.SerializeToString,
            memory__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.MemoryService/Dreaming',
            memory__pb2.DreamRequest.SerializeToString,
            memory__pb2.DreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.MemoryService/GetProjectContext',
            memory__pb2.ProjectRequest.SerializeToString,
            memory__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
